### ISSUE TITLE
挺好的 给你补些素材

### ISSUE THREAD

**Issue by awsl-dbq** [fgheng/keysound#1]
https://github.com/mattogodoy/hacker-sounds/tree/master/audio

https://github.com/timmyreilly/TypewriterNoises-VSCode/tree/master/audio

第一个声音才酷一点

另外基本上就是读 /dev/input/event4 的内容

**Comment by fgheng** [comment]
嗯嗯，非常感谢，有时间我在仔细研究下这方面的内容，您的素材收下了哈

**Comment by awsl-dbq** [comment]
> 嗯嗯，非常感谢，有时间我在仔细研究下这方面的内容，您的素材收下了哈

不客气..
俺在https://github.com/LiaoBill/keyboard_sounds 的基础上 自己fork了个
https://github.com/awsl-dbq/keyboard_sounds
编译了下,可以跑. 它是拿https://www.sfml-dev.org/tutorials/2.5/start-linux.php 这个库去读键盘事件,
不用自己封装.

**Comment by fgheng** [comment]
你好，我更新了，现在可以自定义每个按键的音效了

**Comment by awsl-dbq** [comment]
> 你好，我更新了，现在可以自定义每个按键的音效了

okay, I'll try it later.
