### ISSUE TITLE
自己添加了新声音与json，没有效果

### ISSUE THREAD

**Issue by SenlinOS** [fgheng/keysound#11]
你好，很喜欢你这个项目。

默认的项目声音与json都可以使用，但我想自己加新的效果，但没成功。
所以我把声音文件发给你，这些音效都是自由的，可以自由使用。

“typewriter-dog” 打字机与狗，共5个音效：delete.wav 的音效是狗叫声，我感觉这样会很有趣与好玩；enter.wav 的音效是打字机那种带铃声的音效。

ZIP包：https://raw.githubusercontent.com/SenlinOS/databox/master/typewriter-dog.zip

**Comment by SenlinOS** [comment]
不好意思，我找到原因了，你的**keysound**项目没问题，自定义可以运行～

- 问题是我转换音频的格式不对：我使用Blender转换音频，格式我选择了“U8”，这样文件更小！但这样**keysound**就不支持了，所以使用默认的**S16**就可以了。

我已经更新了1楼的**ZIP包**，包里面现在是**S16**的音频文件了，我还附加了一个**typewriter-dog.json**文件，都放到audio目录里就可以了。

你可以把这个ZIP包文件合并到你的项目里，也可以不合并，你的自由～笑
那么我关闭这个问题了～

**Comment by fgheng** [comment]
你好，你可以提交一个merge request，我可以将音效合并进来
