### ISSUE TITLE
error occured while connect audio

### ISSUE THREAD

**Issue by CptGit** [fgheng/keysound#4]
I tried the example `./keysound -j ./audio/piano.json` but saw the error message "error occured while connect audio". Also ran "./keysound -f ./audio/typewriter-key.wav" but no luck.

**Comment by fgheng** [comment]
hello, please tell me which backend do you use? alsa pulse or sdl? and have you add user to the input group?

**Comment by CptGit** [comment]
> hello, please tell me which backend do you use? alsa pulse or sdl? and have you add user to the input group?

Sorry I was running with Ubuntu 20.04, pulse. Yes I added user to the input group.

**Comment by fgheng** [comment]
Do you run this under root? do not run it under root.

**Comment by CptGit** [comment]
> Do you run this under root? do not run it under root.

After logging out and relogin, it works! I like the piano sound, so interesting :)

**Comment by fgheng** [comment]
haha, thank you.
