### ISSUE TITLE
Error occurred while connect audio

### ISSUE THREAD

**Issue by SkibbleBip** [fgheng/keysound#9]
When running the program with sudo, at /src/Play.cc:318 pa_simple_new() returns NULL. When adding perror() after `if(!s){` it displays `Socket operation on non-socket`. the error code returned by pa_simple_new() is '1'. Other than that, the program is able to read the input event files. It seems the pulse audio server is unable to be connected to on my machine when the software is run as root.

Current Linux environment: Ubuntu 20.04.2 LTS x86_64, pulseaudio 13.99.1

**Comment by fgheng** [comment]
Please try to run it without sudo.

**Comment by SkibbleBip** [comment]
When running without sudo, I get the error:
`Error occured while attempting to open event file: /dev/input/event4 you may not have access to the file`

**Comment by fgheng** [comment]
oh, I see,
you should add yourself to the `input` group

```
sudo usermod -a -G input your_user_name
```

and then logout and relogin or use the command
```
newgrp input
```

**Comment by fgheng** [comment]
Does  that solve the problem for you?

**Comment by SkibbleBip** [comment]
Sorry for the delay, had time this morning to test it out.

Yes, it does work now. Adding my user to the input group allows the sounds to play now.

**Comment by siduck** [comment]
@fgheng Adding the user to group removed that error but i get this error now 

cflag alsa -> 
![image](https://user-images.githubusercontent.com/59060246/177094198-2d5251ff-fe73-4947-af51-ddd00d2a0e98.png)

help :c

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/177094500-b1e95047-bc09-4a5d-9ff1-b2493b3d09d6.png)

tried pulse flag
